[project]
name = "translator-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "torch==2.2.0",
    "transformers>=4.57.0",
    "uvicorn>=0.37.0",
]
